#!/bin/sh /etc/rc.common
USE_PROCD=1
START=95
STOP=10

start_service() {
    procd_open_instance
    procd_set_param command /usr/sbin/watchcat-plus daemon
    procd_set_param respawn 300 5 5
    # Monitor the configuration for reloads
    procd_set_param file /etc/config/watchcat-plus
    procd_close_instance
}

reload_service() {
    # Simple reload implementation: stop and start
    stop
    start
}

service_triggers() {
    # Trigger reload when configuration changes
    procd_add_reload_trigger "watchcat-plus"
}